### PR TITLE
 isuue #86 links in where field.

### PR DESCRIPTION
**Pull request by mitulvaghamshi**

### CODE REVIEW

**Review by rodneybarnes — APPROVED** [review]

**Comment by mitulvaghamshi** [comment]
image

I still can't merge this,
The base branch restricts merging to authorized users.

**Comment by rodneybarnes** [comment]
I just updated our settings, are you able to merge now?

**Comment by mitulvaghamshi** [comment]
https://docs.github.com/articles/what-are-the-different-access-permissions
image

still not.

**Comment by rodneybarnes** [comment]
Ah I see - I would need to make "write access" the base permission. I'll have to check with the rest of the team before making that change; for now, I'll merge your PR myself. Thanks for your patience with this!

**Comment by mitulvaghamshi** [comment]
Alright, thanks, 
do we have any specific channel on Discord where we can easily discuss there issues.

**Comment by rodneybarnes** [comment]
We are setting up a Discord server for the club, and there will be a channel there to discuss work around the website and this repo, but we're currently in the process of preparing it for our event next Friday. For now, feel free to message me directly on Discord - my handle is `Barnes#8650`

**Pull request merged**
